schema_version: 1
train_config:
  __class__: openpi.training.config.TrainConfig
  fields:
    name: act_brainco_revo3_0708_chunk16
    project_name: imitation
    exp_name: act_brainco_revo3_0708_chunk16
    model:
      __class__: openpi.models.act_config.ACTConfig
      fields:
        action_dim: 56
        action_horizon: 16
        max_token_len: 1
        dtype: float32
        hidden_dim: 512
        num_heads: 8
        dim_feedforward: 3200
        num_encoder_layers: 4
        num_decoder_layers: 7
        num_cvae_layers: 4
        dropout: 0.1
        latent_dim: 32
        kl_weight: 10.0
        vision_backbone: resnet18
    weight_loader:
      __class__: openpi.training.weight_loaders.NoOpWeightLoader
      fields: {}
    pytorch_weight_path: null
    pytorch_training_precision: bfloat16
    lr_schedule:
      __class__: openpi.training.optimizer.CosineDecaySchedule
      fields:
        warmup_steps: 1000
        peak_lr: 0.0001
        decay_steps: 40000
        decay_lr: 1.0e-05
    optimizer:
      __class__: openpi.training.optimizer.AdamW
      fields:
        b1: 0.9
        b2: 0.95
        eps: 1.0e-08
        weight_decay: 1.0e-10
        clip_gradient_norm: 1.0
    ema_decay: null
    freeze_strategy: none
    data:
      __class__: openpi.training.config.LeRobotBrainCoDataConfig
      fields:
        repo_id: brainco_revo3_0708_act_chunk16
        assets:
          __class__: openpi.training.config.AssetsConfig
          fields:
            assets_dir: ./assets/pi05_brainco_revo3_pick_place_56d_0708
            asset_id: brainco_revo3_pick_place_56d_0708
        base_config:
          __class__: openpi.training.config.DataConfig
          fields:
            repo_id: null
            asset_id: null
            norm_stats: null
            repack_transforms:
              __class__: openpi.transforms.Group
              fields:
                inputs: []
                outputs: []
            data_transforms:
              __class__: openpi.transforms.Group
              fields:
                inputs: []
                outputs: []
            model_transforms:
              __class__: openpi.transforms.Group
              fields:
                inputs: []
                outputs: []
            use_quantile_norm: false
            action_sequence_keys:
              - actions
            prompt_from_task: true
            rlds_data_dir: null
            action_space: null
            datasets: []
            lerobot_datasets:
              - __class__: openpi.training.config.LeRobotDataset
                fields:
                  repo_id: /mnt/data_nas/ruibin/dataset/7-8-21-18/revotron_mit_revo3_mit_3cam_7-8-21-18_drop_42_45_gop10
                  weight: 1.0
                  asset_id: null
            multi_dataset_mode: concat
        extra_delta_transform: true
        arm_dof: 7
        hand_dof: 21
        head_camera_key: observation.images.cam_head
        revo3_eef_joint_hand_to_joint_hand: true
        action_sequence_keys:
          - action
    assets_base_dir: ./assets
    checkpoint_base_dir: ./checkpoints
    seed: 42
    batch_size: 16
    num_workers: 8
    num_train_steps: 40000
    log_interval: 10
    save_interval: 4000
    keep_period: 4000
    save_final_checkpoint: true
    overwrite: false
    resume: false
    wandb_enabled: true
    policy_metadata: null
    fsdp_devices: 1
