schema_version: 1
train_config:
  __class__: openpi.training.config.TrainConfig
  fields:
    name: pi05_brainco_56d
    project_name: imitation
    exp_name: pi05_0713_merged_action_interface_only
    model:
      __class__: openpi.models.pi0_config.Pi0Config
      fields:
        pi05: true
        action_dim: 56
        action_horizon: 16
        max_token_len: 256
        paligemma_variant: gemma_2b
        action_expert_variant: gemma_300m
    weight_loader:
      __class__: openpi.training.weight_loaders.PartialCheckpointWeightLoader
      fields:
        params_path: gs://openpi-assets/checkpoints/pi05_base/params
    lr_schedule:
      __class__: openpi.training.optimizer.CosineDecaySchedule
      fields:
        warmup_steps: 1000
        peak_lr: 5.0e-05
        decay_steps: 40000
        decay_lr: 5.0e-06
    ema_decay: null
    freeze_strategy: action_interface_only
    data:
      __class__: openpi.training.config.LeRobotBrainCoDataConfig
      fields:
        repo_id: brainco_0713_merged_action56
        base_config:
          __class__: openpi.training.config.DataConfig
          fields:
            prompt_from_task: true
            lerobot_datasets:
              - __class__: openpi.training.config.LeRobotDataset
                fields:
                  repo_id: /mnt/workspace/dataset/revotron_mit_revo3_mit_3cam_pick_and_place_0713_merged
                  weight: 1.0
            multi_dataset_mode: concat
        extra_delta_transform: true
        arm_dof: 7
        hand_dof: 21
        head_camera_key: observation.images.cam_head
        revo3_eef_joint_hand_to_joint_hand: true
    batch_size: 16
    num_workers: 8
    num_train_steps: 40000
    log_interval: 10
    save_interval: 4000
    keep_period: 4000
    wandb_enabled: true
